### PR TITLE
Added company to "We are using" section

### PR DESCRIPTION
**Pull request by nikhog**
After the introduction of Lighthouse v.6. we switched to Preact, which helped us greatly performance-wise. Submitting my company to the list, in-case you'd like to include us in your showcase!

### CODE REVIEW

**Comment by developit** [comment]
Looks good! The logo can be compressed by 74% without changing its quality or filetype:

image (9)

**Comment by nikhog** [comment]
I compressed the logo and got it down to beneath 4kb. I'm still bit of a Github noob though. Hopefully im doing this right.

**Comment by nikhog** [comment]
@developit I compressed the logo and got it down to beneath 4kb. Is it ok to merge now?

**Review by developit — APPROVED** [review]
Yep! Looks good to me!

**Pull request merged**
