### PR TITLE
fix: blog page title invisible issue

### PR DESCRIPTION
**Pull request by n0hack**
## What is this PR?

I have fixed the issue of the post titles being invisible on the blog page. It was found to be influenced by the parent styles, and I have temporarily addressed it using `!important`.

### Before

image

### After

image

### CODE REVIEW

**Comment by rschristian** [comment]
Ah shoot, I must've broken in with #1012. Probably need to limit those styles entirely to `content-region[name*='guide']`

**Comment by n0hack** [comment]
@rschristian then enclosing only this part with `content-region[name*='guide']` should be sufficient?

**markdown.less**
```css
content-region[name*='guide'] {
	a {
		opacity: 0;
		display: inline-flex;
		width: 1.5rem;
		margin-left: -1.5rem;
		&::before {
			content: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="%23fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 7h3a5 5 0 0 1 5 5 5 5 0 0 1-5 5h-3m-6 0H6a5 5 0 0 1-5-5 5 5 0 0 1 5-5h3"></path><line x1="8" y1="12" x2="16" y2="12"></line></svg>');
		}
	}
}
```

**Comment by rschristian** [comment]
Something along those lines I think, yeah. Not 100% sure off the top of my head, would need to test it

**Comment by n0hack** [comment]
I'll go ahead with the translation work first, and I'll test this later

**Pull request closed without merging**
