### PR TITLE
Progressive hydration

### PR DESCRIPTION
**Pull request by developit**
cheap way to get a netlify preview.

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
This looks great and I'm excited about an even faster user experience :tada: On the instance netlify deployed I'm not able to open the menus anymore (same for mobile). No error is thrown in the console but something seems to be going on.

**Comment by developit** [comment]
Hmm, weird - I'm able to open them on the deploy preview. Seeing some funky stuff with the ToC being hidden though.

**Comment by marvinhagemeister** [comment]
Just checked again and everything seems to work now. Not sure what was up with my phone. Clicking on menus works fine for me again (probably something on my end).

**Comment by marvinhagemeister** [comment]
Brought the latest changes from master into this PR to get the CI fix and the correct lockfile.

**Comment by developit** [comment]
its READY!

**Comment by marvinhagemeister** [comment]
Super awesome! Just clicked through a production build and it's as snappy as it has ever been! :+1: 

The only issue I found so far is that the `Hydrators` render an empty tag when in development mode (sidebar missing etc). I was able to track it down to the toc never being set because that happens only during prerendering.

**Comment by developit** [comment]
@marvinhagemeister ToC works in dev mode now.

**Pull request merged**
