### PR TITLE
Markdown worker

### PR DESCRIPTION
**Pull request by developit**
Depends on #379 (retarget once merged).

Note: I split this out because I'm not sure if it's better or worse for performance. This PR will get a Netlify preview that we can use to compare against the one in #379 via webpagetest.org/easy.

### CODE REVIEW

**Comment by developit** [comment]
weird.. no travis?

**Comment by marvinhagemeister** [comment]
@developit The CI only runs when the target branch is `master` :+1:

**Comment by developit** [comment]
Ah, I'm silly

**Comment by marvinhagemeister** [comment]
Nah, don't say that. It happens to everyone :slightly_smiling_face:

**Comment by developit** [comment]
Lighthouse perf score: 97
https://www.webpagetest.org/result/190808_A6_84da7676755460c6103a200465af2c54/

**Pull request merged**
