### PR TITLE
Add Etsy to companies using Preact

### PR DESCRIPTION
**Pull request by mq2thez**

### CODE REVIEW

**Review by JoviDeCroock — APPROVED** [review]

**Comment by JoviDeCroock** [comment]
Screenshot 2021-11-15 at 12 16 26

This looks a bit weird 😅 does this look better for you @mq2thez

**Review by marvinhagemeister — COMMENTED** [review]
Awesome, let's add the logo `etsy.svg` file itself too 👍

**Review by ForsakenHarmony — APPROVED** [review]

**Comment by mq2thez** [comment]
@marvinhagemeister @JoviDeCroock You know, adding the icon does sound like a good idea.

**Comment by ForsakenHarmony** [comment]
@mq2thez I'm assuming you have the approval from Etsy to add it?

**Pull request merged**
