### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by dragomano**

### CODE REVIEW

**Review by rschristian — APPROVED** [review]
Thanks!

Just out of curiosity, are you just using the git diff directly to figure out what's changed? I've been loosely thinking about setting up some sort of tooling for the repo to signal which docs/translations need the most help, as some are _very_ out of date, but haven't looked into it too much yet.

**Comment by dragomano** [comment]
I know, it's crazy, but I actually check the commit history for `.md` files once a month!

**Comment by rschristian** [comment]
Fair enough! Hopefully one day this will get a bit easier.

**Comment by dragomano** [comment]
I can suggest [Crowdin](https://crowdin.com/page/open-source-project-setup-request) for you, they offer a free plan for Open Source projects. You will just need [to set up exporting](https://support.crowdin.com/github-integration/) md files from the `en` folder to Crowdin, and importing localized versions from Crowdin to Github.

**Comment by rschristian** [comment]
I'm not sure we're looking for AI translations at the moment, more so a table in an issue that automatically tracks how far off certain documents are.

Will keep that in mind though.

**Comment by dragomano** [comment]
What does this have to do with AI translations? They are optional, you can disable them. For example, I have quite live people translating in my [Light Portal project](https://crowdin.com/project/light-portal) :)

**Comment by dragomano** [comment]
There is a machine translation option in the settings of each project, but it is disabled by default.

sshot-2

**Comment by rschristian** [comment]
Fair enough. I still don't know quite what I'm looking at to be honest, this tool's marketing does not make it clear **what it actually does**.

Will try to take a better look into it at some point though, I'd like to improve the process here and anything's worth trying out.

**Comment by dragomano** [comment]
Yeah, read the docs, read some articles online, check out some reviews on YouTube.

**Pull request merged**
