### PR TITLE
fix: preact-cli document link

### PR DESCRIPTION
**Pull request by takurinton**
https://github.com/preactjs/preact-www/issues/752

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Hey, thanks for the PR.

I just checked on the [main website](https://preactjs.com/cli) and it looks like this correctly links to the [getting started page](https://preactjs.com/cli/getting-started) when I click the link.

What issues are you encountering, might be an issue that causes a discrepancy between local and published, glad to help out where I can.

**Comment by takurinton** [comment]
@JoviDeCroock 

Thank you for your reply.  
This was originally defined as a relative path.
If it's not my misunderstanding, I think I'll move [here](https://github.com/preactjs/preact-www/blob/master/content/ja/cli/getting-started.md).

**Comment by JoviDeCroock** [comment]
Both should work, if we look at the deploy-preview and live-site both work great. I just tested it locally and both work so let's keep it consistent across the whole site, in the [other documentation pages](https://raw.githubusercontent.com/preactjs/preact-www/master/content/pt-br/cli.md) we also link with `/cli/getting-started.md`

**Comment by takurinton** [comment]
@JoviDeCroock

sorry.
There may be a problem with my environment.
confirm.
Thank you very much.

**Comment by JoviDeCroock** [comment]
@takurinton No problem! If I can help out with environment problems feel free to poke me

**Comment by takurinton** [comment]
@JoviDeCroock

I would like to ask another question.
Is the link in the bottom line [here](https://github.com/preactjs/preact-www/blob/master/content/ja/cli.md) correct [here](https://github.com/preactjs/preact-www/blob/master/content/ja/cli/getting-started.md)?

**Comment by JoviDeCroock** [comment]
which links in particular, if you check the live site they work for me. What issue are you seeing?

**Comment by takurinton** [comment]
@JoviDeCroock


If you click here, the page does not exist like this.

image

**Comment by JoviDeCroock** [comment]
Oh yeah in GitHub that's normal, the documentation is meant to be explored on the live site 😅 let's look at the difference, in [your deploy preview](https://deploy-preview-753--preactjs.netlify.app/cli) this getting-started link now links us to GitHub which isn't the intention, we'd like to keep the existing behavior where we stay on our documentation site, you can compare by clicking the same link [here](https://preactjs.com/cli)

**Comment by takurinton** [comment]
@JoviDeCroock

Oh!!!
Ok!! I understood!! Sooooooooryyyyyyy🙇‍♂️  
Thank you!!!

**Comment by JoviDeCroock** [comment]
No problem, glad I could help out!

**Comment by developit** [comment]
(fwiw I totally wish there was a way we could have both work!)

**Pull request closed without merging**
