### PR TITLE
docs: add aliasing docs for vite

### PR DESCRIPTION
**Pull request by ppalone**
- [x] Added docs for aliasing React to Preact in Vite.

### CODE REVIEW

**Comment by ppalone** [comment]
Looks like alias to `preact/compact` is already added if we are using `@preact/preset-vite` https://github.com/preactjs/preset-vite/blob/main/src/index.ts#L156-L162.

**Comment by rschristian** [comment]
I'd lean towards saying this is unnecessary as not only is there a Vite preset doing this (and other useful things) already, but it's included in the official Vite templates.

**Comment by marvinhagemeister** [comment]
Thanks for making this PR! I tend to agree with @rschristian as we mainly added this section for bundlers where we don't have a preset for. In the future, I'm hoping that we can change our doc to have a general "tooling" section or something similar which lists how to best use Preact with tool XY.

**Comment by ppalone** [comment]
@rschristian & @marvinhagemeister Thanks for your input. I'll close this PR.

**Pull request closed without merging**
