### PR TITLE
feat(we-are-using): adding glance.com logo to companies using preact

### PR DESCRIPTION
**Pull request by mohamedfasil**

### CODE REVIEW

**Comment by mohamedfasil** [comment]
cc @developit

**Comment by developit** [comment]
Hiya @mohamedfasil! What is Glance using Preact for?  I poked around on the site and couldn't find it on there, I'm guessing it's used within the lock screen app?

**Comment by mohamedfasil** [comment]
> Hiya @mohamedfasil! What is Glance using Preact for? I poked around on the site and couldn't find it on there, I'm guessing it's used within the lock screen app?

Hey @developit yes we're using it within the lockscreen app, to ship lots of engaging contents like, live streams, live news, polls, quizes etc and more to millions of users
Some samples can be seen here
https://cdn.live.glance.com/astral/v1/index.html?platform=pwa&channel=k9qJ815VWA
https://cdn.live.glance.com/astral/v1/index.html?channel=d16_glance
(these 2 might not work if there's no live stream happening when you're working)
a quiz sample
https://pollman8f78.blob.core.windows.net/pollman/quiz/preview/quiz.html?quizId=1f539e233de64805b1aba7f81659a4d9

**Comment by developit** [comment]
That's pretty awesome 😎

**Review by nmakod — APPROVED** [review]

**Comment by mohamedfasil** [comment]
@developit  can you please approve and merge this PR, or let me know if any changes are needed

**Review by developit — APPROVED** [review]

**Pull request merged**
